version: 0.2

phases:
  install:
    runtime-version:
      python: 3.7
    commands:
      - pip install pylint
  pre_build:
    commands:
      - echo Build started on `date`
      - echo running pylint against code...
      - pylint hello_world.py
artifacts:
  files:
    - hello_world.py
  discard-paths: yes
